/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-15 10:47:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.EducationDao;
import com.pojo.EducationPojo;
import com.dao.ProjectDao;
import com.dao.MessageDao;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/message.jsp", Long.valueOf(1705681954228L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dao.ProjectDao");
    _jspx_imports_classes.add("com.dao.MessageDao");
    _jspx_imports_classes.add("com.pojo.EducationPojo");
    _jspx_imports_classes.add("com.dao.EducationDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String value = (String) session.getAttribute("login");
if (value == null) {
	response.sendRedirect("login.jsp");
	return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>find jobs cards - Bootdey.com</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shadow {\r\n");
      out.write("	box-shadow: 0 0 3px rgb(53 64 78/ 20%) !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rounded {\r\n");
      out.write("	border-radius: 5px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-light {\r\n");
      out.write("	background-color: #f7f8fa !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-primary, .btn-primary, .btn-outline-primary:hover,\r\n");
      out.write("	.btn-outline-primary:focus, .btn-outline-primary:active,\r\n");
      out.write("	.btn-outline-primary.active, .btn-outline-primary.focus,\r\n");
      out.write("	.btn-outline-primary:not(:disabled):not(.disabled):active,\r\n");
      out.write("	.badge-primary, .nav-pills .nav-link.active, .pagination .active a,\r\n");
      out.write("	.custom-control-input:checked ~.custom-control-label:before, #preloader #status .spinner>div,\r\n");
      out.write("	.social-icon li a:hover, .back-to-top:hover, .back-to-home a, ::selection,\r\n");
      out.write("	#topnav .navbar-toggle.open span:hover, .owl-theme .owl-dots .owl-dot.active span,\r\n");
      out.write("	.owl-theme .owl-dots.clickable .owl-dot:hover span, .watch-video a .play-icon-circle,\r\n");
      out.write("	.sidebar .widget .tagcloud>a:hover, .flatpickr-day.selected,\r\n");
      out.write("	.flatpickr-day.selected:hover, .tns-nav button.tns-nav-active,\r\n");
      out.write("	.form-check-input.form-check-input:checked {\r\n");
      out.write("	background-color: #6dc77a !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".badge {\r\n");
      out.write("	padding: 5px 8px;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	letter-spacing: 0.5px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary, .btn-outline-primary:hover, .btn-outline-primary:focus,\r\n");
      out.write("	.btn-outline-primary:active, .btn-outline-primary.active,\r\n");
      out.write("	.btn-outline-primary.focus, .btn-outline-primary:not(:disabled):not(.disabled):active\r\n");
      out.write("	{\r\n");
      out.write("	box-shadow: 0 3px 7px rgb(109 199 122/ 50%) !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary, .btn-outline-primary, .btn-outline-primary:hover,\r\n");
      out.write("	.btn-outline-primary:focus, .btn-outline-primary:active,\r\n");
      out.write("	.btn-outline-primary.active, .btn-outline-primary.focus,\r\n");
      out.write("	.btn-outline-primary:not(:disabled):not(.disabled):active,\r\n");
      out.write("	.bg-soft-primary .border, .alert-primary, .alert-outline-primary,\r\n");
      out.write("	.badge-outline-primary, .nav-pills .nav-link.active, .pagination .active a,\r\n");
      out.write("	.form-group .form-control:focus, .form-group .form-control.active,\r\n");
      out.write("	.custom-control-input:checked ~.custom-control-label:before,\r\n");
      out.write("	.custom-control-input:focus ~.custom-control-label::before,\r\n");
      out.write("	.form-control:focus, .social-icon li a:hover, #topnav .has-submenu.active.active .menu-arrow,\r\n");
      out.write("	#topnav.scroll .navigation-menu>li:hover>.menu-arrow, #topnav.scroll .navigation-menu>li.active>.menu-arrow,\r\n");
      out.write("	#topnav .navigation-menu>li:hover>.menu-arrow, .flatpickr-day.selected,\r\n");
      out.write("	.flatpickr-day.selected:hover, .form-check-input:focus,\r\n");
      out.write("	.form-check-input.form-check-input:checked, .container-filter li.active,\r\n");
      out.write("	.container-filter li:hover {\r\n");
      out.write("	border-color: #6dc77a !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-primary, .btn-primary, .btn-outline-primary:hover,\r\n");
      out.write("	.btn-outline-primary:focus, .btn-outline-primary:active,\r\n");
      out.write("	.btn-outline-primary.active, .btn-outline-primary.focus,\r\n");
      out.write("	.btn-outline-primary:not(:disabled):not(.disabled):active,\r\n");
      out.write("	.badge-primary, .nav-pills .nav-link.active, .pagination .active a,\r\n");
      out.write("	.custom-control-input:checked ~.custom-control-label:before, #preloader #status .spinner>div,\r\n");
      out.write("	.social-icon li a:hover, .back-to-top:hover, .back-to-home a, ::selection,\r\n");
      out.write("	#topnav .navbar-toggle.open span:hover, .owl-theme .owl-dots .owl-dot.active span,\r\n");
      out.write("	.owl-theme .owl-dots.clickable .owl-dot:hover span, .watch-video a .play-icon-circle,\r\n");
      out.write("	.sidebar .widget .tagcloud>a:hover, .flatpickr-day.selected,\r\n");
      out.write("	.flatpickr-day.selected:hover, .tns-nav button.tns-nav-active,\r\n");
      out.write("	.form-check-input.form-check-input:checked {\r\n");
      out.write("	background-color: #6dc77a !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	padding: 8px 20px;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	letter-spacing: 0.5px;\r\n");
      out.write("	transition: all 0.3s;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	background-color: #6dc77a !important;\r\n");
      out.write("	border: 1px solid #6dc77a !important;\r\n");
      out.write("	color: #fff !important;\r\n");
      out.write("	box-shadow: 0 3px 7px rgb(109 199 122/ 50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" {box-sizing: border-box;}\r\n");
      out.write("\r\n");
      out.write("/* Button used to open the contact form - fixed at the bottom of the page */\r\n");
      out.write(".open-button {\r\n");
      out.write("  \r\n");
      out.write("  background-color: #555;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  opacity: 0.8;\r\n");
      out.write("  bottom: 30px;\r\n");
      out.write("  margin-right: auto;\r\n");
      out.write("  margin-left: auot;\r\n");
      out.write("  margin-bottom: 30px;\r\n");
      out.write("  margin-top:10px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The popup form - hidden by default */\r\n");
      out.write(".form-popup {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  right: 15px;\r\n");
      out.write("  border: 3px solid #f1f1f1;\r\n");
      out.write("  z-index: 9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add styles to the form container */\r\n");
      out.write(".form-container {\r\n");
      out.write("  max-width: 300px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write(".form-container input[type=text], .form-container input[type=password] {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  margin: 5px 0 22px 0;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* When the inputs get focus, do something */\r\n");
      out.write(".form-container input[type=text]:focus, .form-container input[type=password]:focus {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for the submit/login button */\r\n");
      out.write(".form-container .btn {\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 16px 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-bottom:10px;\r\n");
      out.write("  opacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add a red background color to the cancel button */\r\n");
      out.write(".form-container .cancel {\r\n");
      out.write("  background-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add some hover effects to buttons */\r\n");
      out.write(".form-container .btn:hover, .open-button:hover {\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container mt-5 pt-4\">\r\n");
      out.write("	\r\n");
      out.write("	<h3 style = \"text-align: center;\">");
      out.write('\r');
      out.write('\n');

	String message =(String) session.getAttribute("msg");
	if(message!= null){
		
		if(message.equals("Message sent successfully")){

      out.write("\r\n");
      out.write("		<h1 style=\"text-align: center; color: blue\">");
      out.print(message );
      out.write("</h1>\r\n");

		}
		else{

      out.write("\r\n");
      out.write("		<h1 style=\"text-align: center; color: red\">");
      out.print(message );
      out.write("</h1>\r\n");

		}
	}
	session.removeAttribute("msg");

      out.write("</h3>\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"row align-items-end mb-4 pb-2\">\r\n");
      out.write("			<div class=\"col-md-8\">\r\n");
      out.write("				<div class=\"section-title text-center text-md-start\">\r\n");
      out.write("					<h4 class=\"title mb-4\">ADMIN PANEL</h4>\r\n");
      out.write("					<p class=\"text-muted mb-0 para-desc\">An admin panel, short for\r\n");
      out.write("						administrative panel, is a web-based or software interface that\r\n");
      out.write("						provides authorized individuals or administrators with the tools\r\n");
      out.write("						and functionalities to manage, monitor, and control various\r\n");
      out.write("						aspects of a system, application, or website.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-12 mt-4 pt-2\">\r\n");
      out.write("				<div class=\"card border-0 bg-light rounded shadow\">\r\n");
      out.write("					<div class=\"card-body p-4\">\r\n");
      out.write("					\r\n");
      out.write("					");
int count = new MessageDao().count(); 
      out.write("\r\n");
      out.write("						<span class=\"badge rounded-pill bg-primary float-md-end mb-3 mb-sm-0\">");
      out.print(count );
      out.write(" CONTACT	</span>\r\n");
      out.write("						<h5>Contact List</h5>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<span class=\"text-muted d-block\"><i class=\"fa fa-home\"\r\n");
      out.write("								aria-hidden=\"true\"></i> <a href=\"#\" target=\"_blank\"\r\n");
      out.write("								class=\"text-muted\">TANMAY</a></span> <span class=\"text-muted d-block\"><i\r\n");
      out.write("								class=\"fa fa-map-marker\" aria-hidden=\"true\"></i> INDIA</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<a href=\"read-message.jsp\" class=\"btn btn-primary\">Read\r\n");
      out.write("								Message</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-12 mt-4 pt-2\">\r\n");
      out.write("				<div class=\"card border-0 bg-light rounded shadow\">\r\n");
      out.write("					<div class=\"card-body p-4\">\r\n");
      out.write("					\r\n");
      out.write("						");
int project_count = new ProjectDao().count(); 
      out.write("\r\n");
      out.write("						<span class=\"badge rounded-pill bg-primary float-md-end mb-3 mb-sm-0\">");
      out.print(project_count );
      out.write(" Projects	</span>\r\n");
      out.write("						<h5>Add Projects</h5>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<span class=\"text-muted d-block\"><i class=\"fa fa-home\"\r\n");
      out.write("								aria-hidden=\"true\"></i> <a href=\"#\" target=\"_blank\"\r\n");
      out.write("								class=\"text-muted\">TANMAY</a></span> <span class=\"text-muted d-block\"><i\r\n");
      out.write("								class=\"fa fa-map-marker\" aria-hidden=\"true\"></i> INDIA</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<a href=\"project.jsp\" class=\"btn btn-primary\">Add Project</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-12 mt-4 pt-2\">\r\n");
      out.write("				<div class=\"card border-0 bg-light rounded shadow\">\r\n");
      out.write("					<div class=\"card-body p-4\">\r\n");
      out.write("						<span class=\"badge rounded-pill bg-primary float-md-end mb-3 mb-sm-0\">");
      out.print(project_count );
      out.write(" Projects	</span>\r\n");
      out.write("						<h5>Update Projects</h5>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<span class=\"text-muted d-block\"><i class=\"fa fa-home\"\r\n");
      out.write("								aria-hidden=\"true\"></i> <a href=\"#\" target=\"_blank\"\r\n");
      out.write("								class=\"text-muted\">TANMAY</a></span> <span class=\"text-muted d-block\"><i\r\n");
      out.write("								class=\"fa fa-map-marker\" aria-hidden=\"true\"></i> INDIA</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<a href=\"update-project.jsp\" class=\"btn btn-primary\">Update Project</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>			\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-12 mt-4 pt-2\">\r\n");
      out.write("				<div class=\"card border-0 bg-light rounded shadow\">\r\n");
      out.write("					<div class=\"card-body p-4\">\r\n");
      out.write("					");
int edu_count = new EducationDao().countEdu();
      out.write("\r\n");
      out.write("						<span class=\"badge rounded-pill bg-primary float-md-end mb-3 mb-sm-0\">");
      out.print(edu_count );
      out.write(" Education	</span>\r\n");
      out.write("						<h5>Education</h5>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<span class=\"text-muted d-block\"><i class=\"fa fa-home\"\r\n");
      out.write("								aria-hidden=\"true\"></i> <a href=\"#\" target=\"_blank\"\r\n");
      out.write("								class=\"text-muted\">TANMAY</a></span> <span class=\"text-muted d-block\"><i\r\n");
      out.write("								class=\"fa fa-map-marker\" aria-hidden=\"true\"></i> INDIA</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<a href=\"education.jsp\" class=\"btn btn-primary\">Edit Education</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"col-lg-4 col-md-6 col-12 mt-4 pt-2\">\r\n");
      out.write("				<div class=\"card border-0 bg-light rounded shadow\">\r\n");
      out.write("					<div class=\"card-body p-4\">\r\n");
      out.write("					\r\n");
      out.write("						<span class=\"badge rounded-pill bg-primary float-md-end mb-3 mb-sm-0\"> Certificates	</span>\r\n");
      out.write("						<h5>Certificates</h5>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<span class=\"text-muted d-block\"><i class=\"fa fa-home\"\r\n");
      out.write("								aria-hidden=\"true\"></i> <a href=\"#\" target=\"_blank\"\r\n");
      out.write("								class=\"text-muted\">TANMAY</a></span> <span class=\"text-muted d-block\"><i\r\n");
      out.write("								class=\"fa fa-map-marker\" aria-hidden=\"true\"></i> INDIA</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"mt-3\">\r\n");
      out.write("							<a href=\"certificates.jsp\" class=\"btn btn-primary\">Edit Certificates</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div style=\"text-align: center; padding-top: 50px;\" class=\"mt-3\">\r\n");
      out.write("			\r\n");
      out.write("			<!-- A button to open the popup form -->\r\n");
      out.write("			<button class=\"open-button\" onclick=\"openForm()\">CHANGE\r\n");
      out.write("				CREDENTIALS</button>\r\n");
      out.write("\r\n");
      out.write("			<!-- The form -->\r\n");
      out.write("			<div class=\"form-popup\" id=\"myForm\">\r\n");
      out.write("				<form action=\"Auth\" method=\"post\" class=\"form-container\">\r\n");
      out.write("					<h2>Change Password</h2>\r\n");
      out.write("\r\n");
      out.write("					<label for=\"email\"><b>Old Password</b></label> <input type=\"text\"\r\n");
      out.write("						placeholder=\"Enter old password\" name=\"opass\" required> <label\r\n");
      out.write("						for=\"psw\"><b>New Password</b></label> <input type=\"password\"\r\n");
      out.write("						placeholder=\"Enter Password\" name=\"npass\" required> <label\r\n");
      out.write("						for=\"psw\"><b>Confirm Password</b></label> <input type=\"password\"\r\n");
      out.write("						placeholder=\"Enter Confirm Password\" name=\"cpass\" required>\r\n");
      out.write("\r\n");
      out.write("					<input type=\"hidden\" name=\"check\" value=\"change\">\r\n");
      out.write("\r\n");
      out.write("					<button type=\"submit\" class=\"btn\">Update</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn cancel\" onclick=\"closeForm()\">Close</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("				<form action=\"Auth\" method=\"post\">\r\n");
      out.write("					<input type =\"hidden\" name = \"check\" value = \"Logout\">\r\n");
      out.write("					<button class=\"btn btn-primary\">LOGOUT</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		function openForm() {\r\n");
      out.write("			document.getElementById(\"myForm\").style.display = \"block\";\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function closeForm() {\r\n");
      out.write("			document.getElementById(\"myForm\").style.display = \"none\";\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
