/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-01-24 10:13:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pojo.Projectpojo;
import java.util.ArrayList;
import com.dao.ProjectDao;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/message.jsp", Long.valueOf(1705681954228L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dao.ProjectDao");
    _jspx_imports_classes.add("com.pojo.Projectpojo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Tanmay's Portfolio</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/unicons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- MAIN STYLE -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/tooplate-style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String message =(String) session.getAttribute("msg");
	if(message!= null){
		
		if(message.equals("Message sent successfully")){

      out.write("\r\n");
      out.write("		<h1 style=\"text-align: center; color: blue\">");
      out.print(message );
      out.write("</h1>\r\n");

		}
		else{

      out.write("\r\n");
      out.write("		<h1 style=\"text-align: center; color: red\">");
      out.print(message );
      out.write("</h1>\r\n");

		}
	}
	session.removeAttribute("msg");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- MENU -->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-sm navbar-light\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"index.html\"><i class='uil uil-user'></i>\r\n");
      out.write("				Tanmay</a>\r\n");
      out.write("\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("				aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span> <span\r\n");
      out.write("					class=\"navbar-toggler-icon\"></span> <span\r\n");
      out.write("					class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("				<ul class=\"navbar-nav mx-auto\">\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"#about\" class=\"nav-link\"><span\r\n");
      out.write("							data-hover=\"About\">About</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"#project\" class=\"nav-link\"><span\r\n");
      out.write("							data-hover=\"Projects\">Projects</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"#resume\" class=\"nav-link\"><span\r\n");
      out.write("							data-hover=\"Resume\">Resume</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"#contact\" class=\"nav-link\"><span\r\n");
      out.write("							data-hover=\"Contact\">Contact</span></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("				<ul class=\"navbar-nav ml-lg-auto\">\r\n");
      out.write("					<div class=\"ml-lg-4\">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"color-mode d-lg-flex justify-content-center align-items-center\">\r\n");
      out.write("							<i class=\"color-mode-icon\"></i> Color mode\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<!-- ABOUT -->\r\n");
      out.write("	<section\r\n");
      out.write("		class=\"about full-screen d-lg-flex justify-content-center align-items-center\"\r\n");
      out.write("		id=\"about\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-7 col-md-12 col-12 d-flex align-items-center\">\r\n");
      out.write("					<div class=\"about-text\">\r\n");
      out.write("						<small class=\"small-text\">Welcome to <span\r\n");
      out.write("							class=\"mobile-block\">my portfolio website!</span></small>\r\n");
      out.write("						<h1 class=\"animated animated-text\">\r\n");
      out.write("							<span class=\"mr-2\">Hey folks, I'm</span>\r\n");
      out.write("							<div class=\"animated-info\">\r\n");
      out.write("								<span class=\"animated-item\">Tanmay Kayande</span> <span\r\n");
      out.write("									class=\"animated-item\">Java Developer</span> <span\r\n");
      out.write("									class=\"animated-item\">Fresher</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</h1>\r\n");
      out.write("\r\n");
      out.write("						<p>Building a successful product is a challenge. I am highly\r\n");
      out.write("							energetic in user experience design, interfaces and web\r\n");
      out.write("							development.</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"custom-btn-group mt-4\">\r\n");
      out.write("							<a href=\"#\" class=\"btn mr-lg-2 custom-btn\"><i\r\n");
      out.write("								class='uil uil-file-alt'></i> Download Resume</a> <a href=\"#contact\"\r\n");
      out.write("								class=\"btn custom-btn custom-btn-bg custom-btn-link\">Get a\r\n");
      out.write("								free quote</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-5 col-md-12 col-12\">\r\n");
      out.write("					<div class=\"about-image svg\">\r\n");
      out.write("						<img src=\"images/undraw/undraw_software_engineer_lvl5.svg\"\r\n");
      out.write("							class=\"img-fluid\" alt=\"svg image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- PROJECTS -->\r\n");
      out.write("	<section class=\"project py-5\" id=\"project\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-11 text-center mx-auto col-12\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("						<h2>My Projects</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"owl-carousel owl-theme\">\r\n");
      out.write("						<!-- loop -->\r\n");
      out.write("\r\n");
      out.write("						");

						ArrayList<Object> al = new ProjectDao().read();

						for (int i = al.size() - 1; i >= 0; i--) {
							Projectpojo p = (Projectpojo) al.get(i);
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"item\">\r\n");
      out.write("							<div class=\"project-info\">\r\n");
      out.write("								<img src=\"images/myprojects/");
      out.print(p.getFilename());
      out.write("\"\r\n");
      out.write("									class=\"img-fluid\" alt=\"project image\"\r\n");
      out.write("									style=\"max-width: 900px; max-height: 500px; margin: auto; display: block;\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!--  <div class=\"item\">\r\n");
      out.write("                          <div class=\"project-info\">\r\n");
      out.write("                            <img src=\"images/myprojects/2024-01-24T121206.905543200FIMO_1680350505253.jpg\" class=\"img-fluid\" alt=\"project image\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                          <div class=\"project-info\">\r\n");
      out.write("                            <img src=\"images/project/project-image03.png\" class=\"img-fluid\" alt=\"project image\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                          <div class=\"project-info\">\r\n");
      out.write("                            <img src=\"images/project/project-image04.png\" class=\"img-fluid\" alt=\"project image\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                          <div class=\"project-info\">\r\n");
      out.write("                            <img src=\"images/project/project-image05.png\" class=\"img-fluid\" alt=\"project image\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div> -->\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- FEATURES -->\r\n");
      out.write("	<section\r\n");
      out.write("		class=\"resume py-5 d-lg-flex justify-content-center align-items-center\"\r\n");
      out.write("		id=\"resume\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-6 col-12\">\r\n");
      out.write("					<h2 class=\"mb-4\">Experiences</h2>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"timeline\">\r\n");
      out.write("						<div class=\"timeline-wrapper\">\r\n");
      out.write("							<div class=\"timeline-yr\">\r\n");
      out.write("								<span>2019</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"timeline-info\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<span>Project Manager</span><small>Best Studio</small>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>Proin ornare non purus ut rutrum. Nulla facilisi. Aliquam\r\n");
      out.write("									laoreet libero ac pharetra feugiat. Cras ac fermentum nunc, a\r\n");
      out.write("									faucibus nunc.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"timeline-wrapper\">\r\n");
      out.write("							<div class=\"timeline-yr\">\r\n");
      out.write("								<span>2018</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"timeline-info\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<span>UX Designer</span><small>Digital Ace</small>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>Fusce rutrum augue id orci rhoncus molestie. Nunc auctor\r\n");
      out.write("									dignissim lacus vel iaculis.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"timeline-wrapper\">\r\n");
      out.write("							<div class=\"timeline-yr\">\r\n");
      out.write("								<span>2016</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"timeline-info\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<span>UI Freelancer \r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>Sed fringilla vitae enim sit amet cursus. Sed cursus\r\n");
      out.write("									dictum tortor quis pharetra. Pellentesque habitant morbi\r\n");
      out.write("									tristique senectus et netus et malesuada fames ac turpis\r\n");
      out.write("									egestas.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"timeline-wrapper\">\r\n");
      out.write("							<div class=\"timeline-yr\">\r\n");
      out.write("								<span>2014</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"timeline-info\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<span>Junior Designer<small>Crafted Co.</small>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>Cras scelerisque scelerisque condimentum. Nullam at\r\n");
      out.write("									volutpat mi. Nunc auctor ipsum eget magna consequat viverra.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-6 col-12\">\r\n");
      out.write("					<h2 class=\"mb-4 mobile-mt-2\">Educations</h2>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"timeline\">\r\n");
      out.write("						<div class=\"timeline-wrapper\">\r\n");
      out.write("							<div class=\"timeline-yr\">\r\n");
      out.write("								<span>2017</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"timeline-info\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<span>Mobile Web</span><small>Master Design</small>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>Please tell your friends about Tooplate website. That\r\n");
      out.write("									would be very helpful. We need your support.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"timeline-wrapper\">\r\n");
      out.write("							<div class=\"timeline-yr\">\r\n");
      out.write("								<span>2015</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"timeline-info\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<span>User Interfaces</span><small>Creative Agency</small>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>\r\n");
      out.write("									<a rel=\"nofollow\" href=\"https://www.facebook.com/tooplate\">Tooplate</a>\r\n");
      out.write("									is a great website to download HTML templates without any login\r\n");
      out.write("									or email.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"timeline-wrapper\">\r\n");
      out.write("							<div class=\"timeline-yr\">\r\n");
      out.write("								<span>2013</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"timeline-info\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<span>Artwork Design</span><small>New Art School</small>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<p>You can freely use Tooplate's templates for your business\r\n");
      out.write("									or personal sites. You cannot redistribute this template\r\n");
      out.write("									without a permission.</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- CONTACT -->\r\n");
      out.write("	<section class=\"contact py-5\" id=\"contact\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-5 mr-lg-5 col-12\">\r\n");
      out.write("					<div class=\"google-map w-100\">\r\n");
      out.write("						<iframe\r\n");
      out.write("							src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12088.558402180099!2d-73.99373482142036!3d40.75895421922642!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25855b8fb3083%3A0xa0f9aef176042a5c!2sTheater+District%2C+New+York%2C+NY%2C+USA!5e0!3m2!1sen!2smm!4v1549875377188\"\r\n");
      out.write("							width=\"400\" height=\"300\" frameborder=\"0\" style=\"border: 0\"\r\n");
      out.write("							allowfullscreen></iframe>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"contact-info d-flex justify-content-between align-items-center py-4 px-lg-5\">\r\n");
      out.write("						<div class=\"contact-info-item\">\r\n");
      out.write("							<h3 class=\"mb-3 text-white\">Say hello</h3>\r\n");
      out.write("							<p class=\"footer-text mb-0\">010 020 0960</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"mailto:hello@company.co\">hello@company.co</a>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"social-links\">\r\n");
      out.write("							<li><a href=\"#\" class=\"uil uil-dribbble\"\r\n");
      out.write("								data-toggle=\"tooltip\" data-placement=\"left\" title=\"Dribbble\"></a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"uil uil-instagram\"\r\n");
      out.write("								data-toggle=\"tooltip\" data-placement=\"left\" title=\"Instagram\"></a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"uil uil-youtube\"\r\n");
      out.write("								data-toggle=\"tooltip\" data-placement=\"left\" title=\"Youtube\"></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-6 col-12\">\r\n");
      out.write("					<div class=\"contact-form\">\r\n");
      out.write("						<h2 class=\"mb-4\">Interested to work together? Let's talk</h2>\r\n");
      out.write("\r\n");
      out.write("						<form action=\"Message\" method=\"post\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-lg-6 col-12\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"name\"\r\n");
      out.write("										placeholder=\"Your Name\" id=\"name\">\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"col-lg-6 col-12\">\r\n");
      out.write("									<input type=\"email\" class=\"form-control\" name=\"email\"\r\n");
      out.write("										placeholder=\"Email\" id=\"email\">\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"col-12\">\r\n");
      out.write("									<textarea name=\"message\" rows=\"6\" class=\"form-control\"\r\n");
      out.write("										id=\"message\" placeholder=\"Message\"></textarea>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"ml-lg-auto col-lg-5 col-12\">\r\n");
      out.write("									<input type=\"submit\" class=\"form-control submit-btn\"\r\n");
      out.write("										value=\"Send Button\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- FOOTER -->\r\n");
      out.write("	<footer class=\"footer py-5\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-12 col-12\">\r\n");
      out.write("					<p class=\"copyright-text text-center\">Copyright &copy; 2019\r\n");
      out.write("						Company Name . All rights reserved</p>\r\n");
      out.write("					<p class=\"copyright-text text-center\">\r\n");
      out.write("						Designed by <a rel=\"nofollow\"\r\n");
      out.write("							href=\"https://www.facebook.com/tooplate\">Tooplate</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("	<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"js/Headroom.js\"></script>\r\n");
      out.write("	<script src=\"js/jQuery.headroom.js\"></script>\r\n");
      out.write("	<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"js/smoothscroll.js\"></script>\r\n");
      out.write("	<script src=\"js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
